version: 2.1

workflows:
  test-deploy:
    jobs:
      - test-build

jobs:
  test-build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: 
          name: Test the build
          command: npm run test 